stages:
  - build
  - test
  - quality
  - deploy
  - publish

before_script:
  - export NOW=$(date +"%Y%m%d-%H%M%S")
  - export TAR_NAME_POSTFIX=$NOW
  - export SYS=`uname -s`
  - export CHAOS_LIB_HASH=`git log -n 1 --pretty="%h"`
  - export NPROC=$(nproc --ignore 1)
  - export ARCH=`uname -m`
  - export CHAOS_LIB_HASH=`git log -n 1 --pretty="%h"`;
  - export HEAPCHECK=strict

build_ubuntu_14_04_gcc49:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/14:gcc_49
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_ARCHITECTURE_TEST=ON -DCHAOS_SANITIZER=TestFramework -DCMAKE_BUILD_TYPE=PROFILE .
    - make clean
    - /tmp/build-wrapper/build-wrapper-linux-x86-64 --out-dir bw-output make -j $NPROC install
  cache:
    key: x86_64_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - ChaosMetadataService
        - chaos_metadata_service_client
        - chaos_micro_unit_toolkit
        - chaos_service_common
        - ccs
        - CHAOSFrameworkTests
        - bw-output
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

build_ubuntu_14_04_gcc49_test:
  dependencies:
    - build_ubuntu_14_04_gcc49
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/14:gcc_49
  script:
    - apt-get update
    - apt-get -y install lcov
    - export PPROF_PATH=chaos-distrib-x86_64-Linux/bin/pprof
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
    - export HEAPCHECK=normal
    - chaos-distrib-x86_64-Linux/bin/TestFramework --gtest_output=xml:report_test.xml --gtest_repeat=10 --gtest_break_on_failure
    - lcov -c -d chaos --output-file coverage.info
    - genhtml coverage.info --output-directory coverage_html
    - /tmp/sonar-scanner/bin/sonar-scanner
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.projectKey=chaosframework
      -Dsonar.organization=bisegni-github
      -Dsonar.sources=chaos,ChaosMetadataService,chaos_metadata_service_client,chaos_micro_unit_toolkit,chaos_service_common,ccs
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.login=369dba58f43885fc41db2f9076a67b36aa5b2584
      -Dsonar.cfamily.build-wrapper-output=bw-output
      -Dsonar.cfamily.threads=$NPROC
      -Dsonar.cfamily.gcov.reportsPath=.
      -Dsonar.cxx.xunit.reportPath=repost_test.xml
  artifacts:
    paths:
        - 'coverage_html'
    expire_in: 1 hour
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  only:
    - tags
    - web
  retry: 2

build_ubuntu_16_04_gcc5:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/16:llvm6
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_ARCHITECTURE_TEST=ON -DUSE_GPT=ON .
    - make clean
    - make  -j $NPROC
    - make install
#    - cd ccs
#    - /Qt/5.9.3/gcc_64/bin/qmake
#    - make -j $NPROC
  cache:
    key: UBUNTU_1604_LLVM7_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - CHAOSFrameworkTests
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

build_ubuntu_16_04_gcc5_test:
  dependencies:
    - build_ubuntu_16_04_gcc5
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/16:llvm6
  script:
  - export PPROF_PATH=chaos-distrib-x86_64-Linux/bin/pprof
  - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
  - export HEAPCHECK=normal
  - chaos-distrib-x86_64-Linux/bin/TestFramework --gtest_repeat=10 --gtest_break_on_failure
  artifacts:
    paths:
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

build_ubuntu_18_04_gcc73:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/18:gcc7.3
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_ARCHITECTURE_TEST=ON -DUSE_GPT=ON .
    - make clean
    - make  -j $NPROC
    - make install
#    - cd ccs
#    - /Qt/5.9.3/gcc_64/bin/qmake
#    - make -j $NPROC
  cache:
    key: UBUNTU_1604_LLVM7_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - CHAOSFrameworkTests
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

build_ubuntu_18_04_gcc73_test:
  dependencies:
    - build_ubuntu_18_04_gcc73
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/18:gcc7.3
  script:
  - export PPROF_PATH=chaos-distrib-x86_64-Linux/bin/pprof
  - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
  - export HEAPCHECK=normal
  - chaos-distrib-x86_64-Linux/bin/TestFramework --gtest_repeat=10 --gtest_break_on_failure
  artifacts:
    paths:
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2


build_framework_centos7:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/centos7:devtools7
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_VERSION_MAJOR="$CI_COMMIT_REF_NAME.$CHAOS_LIB_HASH" -DCHAOS_VERSION_MINOR="$CI_JOB_STAGE.$CI_COMMIT_SHA" -DCHAOS_BUILD_ID=${CI_PIPELINE_ID} -DCHAOS_ARCHITECTURE_TEST=ON -DUSE_GPT=ON .
    - make clean
    - make  -j $NPROC
    - make install
#    - cd ccs
#    - /Qt/5.9.3/gcc_64/bin/qmake
#    - make -j $NPROC
#    - mv /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-centos7
  cache:
    key: x86_64_centos7_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - CHAOSFrameworkTests
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

build_framework_centos7_test:
  dependencies:
    - build_framework_centos7
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/centos7:devtools7
  script:
    - export PPROF_PATH=chaos-distrib-x86_64-Linux/bin/pprof
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
    - export HEAPCHECK=normal
    - chaos-distrib-x86_64-Linux/bin/TestFramework --gtest_repeat=10 --gtest_break_on_failure
  artifacts:
    paths:
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

framework_centos7_deploy:
  allow_failure: true
  tags:
    - chaos
    - docker
    - linux
    - fast
    - infncc
    - lnf
  stage: deploy
  image: baltig.infn.it:4567/chaos-lnf-control/chaos_bundle_compilation:lite
  dependencies:
    - build_framework_centos7_test
  script:
    - echo "Prearing deploy for chaos-distrib-x86_64-centos7_$TAR_NAME_POSTFIX.tar.gz"
    - tar cfz chaos-distrib-x86_64-centos7_$TAR_NAME_POSTFIX.tar.gz chaos-distrib-x86_64-Linux
    - ls -la
    - scp chaos-distrib-x86_64-centos7_$TAR_NAME_POSTFIX.tar.gz chaosweb@opensource.lnf.infn.it:/var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/x86_64/centos/7/chaos-distrib-$TAR_NAME_POSTFIX.tar.gz
    - ssh chaosweb@opensource.lnf.infn.it "rm -f /var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/x86_64/centos/7/latest"
    - ssh chaosweb@opensource.lnf.infn.it "ln -sf /var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/x86_64/centos/7/chaos-distrib-$TAR_NAME_POSTFIX.tar.gz /var/www/html/binary/chaos/$CI_COMMIT_REF_NAME/x86_64/centos/7/latest"
    - curl -X POST -F token=d42ffdee47536fd7cfac5ec4df9af2 -F "ref=$CI_COMMIT_REF_NAME" https://baltig.infn.it/api/v4/projects/1328/trigger/pipeline
  only:
    - tags
    - web
  retry: 2

build_ubuntu_14_04_gcc48_c98:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/14:gcc
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_ENABLE_C11=OFF -DCHAOS_MDS=OFF -DCHAOS_ARCHITECTURE_TEST=ON  -DUSE_GPT=ON -DCMAKE_BUILD_TYPE=PROFILE .
    - make clean
    - make  -j $NPROC
    - make install
    # - mv /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux-c98
  cache:
    key: x86_64_c98_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

build_ubuntu_14_04_gcc48_c98_test:
  dependencies:
    - build_ubuntu_14_04_gcc48_c98
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/ubuntu/14:gcc
  script:
    - export PPROF_PATH=chaos-distrib-x86_64-Linux/bin/pprof
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
    - export HEAPCHECK=normal
    - chaos-distrib-x86_64-Linux/bin/TestFramework --gtest_repeat=10 --gtest_break_on_failure
  only:
    - tags
    - web
  retry: 2

build_framework_arm:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation:latest
  script:
    - tools/chaos_clean.sh
    - cmake -DCHAOS_TARGET=armhf -DCHAOS_MDS=OFF .
    - make clean
    - make  -j $NPROC
    - make install
  cache:
    key: arm-compilation_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - 'chaos-distrib-armhf'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

llvm_build_framework_x86_64:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/llvm_coverity_u1710
  script:
    - tools/chaos_clean.sh
    - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCHAOS_ARCHITECTURE_TEST=ON  -DUSE_GPT=ON .
    - make clean
    - make  -j $NPROC
    - make install
    # - mv /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux-llvm
  cache:
    key: llvm_x86_64_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  artifacts:
    paths:
        - chaos
        - CHAOSFrameworkTests
        - 'chaos-distrib-x86_64-Linux'
    expire_in: 8 hour
  only:
    - tags
    - web
  retry: 2

llvm_build_framework_x86_64_test:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: test
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/llvm_coverity_u1710
  dependencies:
    - llvm_build_framework_x86_64
  script:
    - export PPROF_PATH=chaos-distrib-x86_64-Linux/bin/pprof
    - export LD_LIBRARY_PATH=/builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/lib
    - export HEAPCHECK=normal
    - chaos-distrib-x86_64-Linux/bin/TestFramework --gtest_repeat=10 --gtest_break_on_failure
  only:
    - tags
    - web
  retry: 2

exp_llvm_scan_coverity:
  tags:
    - chaos
    - docker
    - linux
    - fast
  stage: build
  image: baltig.infn.it:4567/bisegni/chaos-docker-compilation/llvm_coverity_u1710
  script:
    - mkdir -p /tmp/cov-int
    - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCHAOS_ARCHITECTURE_TEST=ON .
    - make clean
    - /tmp/coverity/bin/cov-build --dir /tmp/cov-int make -j 4
    - cd /tmp
    - tar czvf chaos.tgz cov-int
    - curl --form token=i9B9MI9n53zWdx2iSS4Qvg --form email=bisegni@lnf.infn.it --form file=@/tmp/chaos.tgz --form version="1.0.0" --form description="Beta"  https://scan.coverity.com/builds?project=%21CHAOS+Control+System
  cache:
    key: scan_coverity_$CI_BUILD_REF_NAME
    paths:
        - /builds/chaos-lnf-control/chaosframework/chaos-distrib-x86_64-Linux/
        - /builds/chaos-lnf-control/chaosframework/config/CACHE/
  only:
    - schedules
  retry: 2

pages:
  stage: publish
  dependencies:
    - build_ubuntu_14_04_gcc49_test
  script:
    - mv coverage_html public
    - ls -la
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - tags
    - web
